# Generated by Django 5.2.5 on 2025-09-23 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp1", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskupdate",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RemoveField(
            model_name="task",
            name="completion_notes",
        ),
        migrations.RemoveField(
            model_name="taskupdate",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="taskupdate",
            name="update_message",
        ),
        migrations.AddField(
            model_name="taskupdate",
            name="comment",
            field=models.TextField(default="pending"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taskupdate",
            name="new_status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="taskupdate",
            name="previous_status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="taskupdate",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="employee_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
