# Generated by Django 5.2.5 on 2025-09-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp1", "0002_alter_taskupdate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskupdate",
            name="update_message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
